# Generated by Django 6.0.3 on 2026-03-05 09:52

import django.db.models.deletion
import rooms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('invite_code', models.CharField(default=rooms.models.generate_invite_code, max_length=8, unique=True)),
                ('color_theme', models.CharField(choices=[('#6C63FF', 'Purple'), ('#FF6584', 'Pink'), ('#43B97F', 'Green'), ('#3B82F6', 'Blue'), ('#F59E0B', 'Amber'), ('#EF4444', 'Red'), ('#8B5CF6', 'Violet'), ('#06B6D4', 'Cyan'), ('#EC4899', 'Rose'), ('#14B8A6', 'Teal')], default='#6C63FF', max_length=7)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='room_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_teaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('removed', 'Removed')], default='approved', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rooms.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('room', 'student')},
            },
        ),
    ]
