# Generated by Django 6.0.3 on 2026-03-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='color_theme',
            field=models.CharField(choices=[('#3A4B54', 'Slate Blue'), ('#5C504A', 'Warm Taupe'), ('#485E5A', 'Sage Green'), ('#605068', 'Dusky Plum'), ('#4A5468', 'Steel Blue'), ('#684A4A', 'Rust Red'), ('#52584C', 'Olive Drab'), ('#4A5F68', 'Ocean Slate'), ('#68554A', 'Burnt Siena'), ('#2D2D2D', 'Charcoal')], default='#6C63FF', max_length=7),
        ),
    ]
