# Generated by Django 6.0.3 on 2026-03-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='color_theme',
            field=models.CharField(choices=[('#3A4B54', 'Slate Blue'), ('#5C504A', 'Warm Taupe'), ('#485E5A', 'Sage Green'), ('#605068', 'Dusky Plum'), ('#4A5468', 'Steel Blue'), ('#684A4A', 'Rust Red'), ('#52584C', 'Olive Drab'), ('#4A5F68', 'Ocean Slate'), ('#68554A', 'Burnt Sienna'), ('#2D2D2D', 'Charcoal')], default='#3A4B54', max_length=7),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('removed', 'Removed')], db_index=True, default='approved', max_length=10),
        ),
    ]
