server {
    server_name isetkl-classroom.gleeze.com;

    client_max_body_size 100M;

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /home/ubuntu/eduroom/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/eduroom/media/;
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods 'GET, OPTIONS' always;
        add_header Access-Control-Allow-Headers 'Authorization, Range' always;
        add_header Content-Disposition 'inline' always;
        expires 7d;
    }

    location / {
        root /home/ubuntu/eduroom/frontend/dist;
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/isetkl-classroom.gleeze.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/isetkl-classroom.gleeze.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name isetkl-classroom.gleeze.com;
    return 301 https://$host$request_uri;
}

server {
    listen 80 default_server;
    server_name 13.51.58.5 _;
    return 301 https://isetkl-classroom.gleeze.com$request_uri;
}
