# Generated by Django 6.0.3 on 2026-03-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_user_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_version', models.CharField(default='1.0.0', help_text='Minimum required app version (semver, e.g. 2.1.0)', max_length=20)),
                ('is_locked', models.BooleanField(default=False, help_text='When enabled, users with an older version will be forced to update.')),
                ('lock_message', models.TextField(default='A new version of the app is available. Please update to continue.', help_text='Message displayed to users when the app is locked.')),
                ('update_url', models.URLField(blank=True, default='', help_text='URL where users can download the latest APK.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Version Config',
                'verbose_name_plural': 'App Version Config',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
