# Generated by Django 5.2.12 on 2026-03-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_app_version_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('message', models.TextField(default="Une nouvelle mise à jour est disponible. Veuillez l'installer pour continuer.")),
                ('update_link', models.URLField(default='https://isetkl-classroom.gleeze.com/download')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AppVersionConfig',
        ),
    ]
