# Generated by Django 5.2.12 on 2026-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appversion_delete_appversionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='version_name',
            field=models.CharField(default='1.0', max_length=50, unique=True),
        ),
    ]
