import React, { createContext, useContext, useState, useEffect } from "react";

export type Lang = "fr" | "en" | "ar_tn";

const translations = {
  fr: {
    good_morning: "Bonjour",
    good_afternoon: "Bon après-midi",
    good_evening: "Bonsoir",
    your_rooms: "Vos salles",
    no_rooms: "Aucune salle",
    create_room: "Créer une salle",
    join_room: "Rejoindre",
    my_grades: "Mes notes",
    refresh: "Actualiser",
    home: "Accueil",
    explore: "Explorer",
    grades: "Notes",
    notifications: "Alertes",
    profile: "Profil",
    create: "Créer",
    content: "Contenu",
    tasks: "Devoirs",
    news: "Annonces",
    no_content: "Aucun contenu",
    no_assignments: "Aucun devoir",
    no_announcements: "Aucune annonce",
    loading: "Chargement...",
    error: "Erreur",
    cancel: "Annuler",
    save: "Enregistrer",
    submit: "Soumettre",
    delete: "Supprimer",
    leave_room: "Quitter la salle",
    add_section: "Ajouter une section",
    add_content: "Ajouter du contenu",
    add_assignment: "Ajouter un devoir",
    add_announcement: "Faire une annonce",
    your_submission: "Votre soumission",
    submitted: "Soumis",
    graded: "Noté",
    settings: "Paramètres",
    language: "Langue",
    logout: "Déconnexion",
    version: "Version",
    made_by: "Fait par",
    enter_code: "Code d'invitation...",
    join: "Rejoindre",
    mark_all_read: "Tout marquer lu",
    delete_all: "Tout supprimer",
    no_notifications: "Aucune notification",
    overall_avg: "Moyenne",
    rooms: "Salles",
    no_grades: "Aucune note",
    welcome_back: "Bon retour",
    sign_in: "Se connecter",
    create_account: "Créer un compte",
    comments: "Commentaires",
    add_comment: "Ajouter un commentaire...",
    post: "Publier",
    no_comments: "Aucun commentaire",
    no_deadline: "Pas de délai",
    past_due: "En retard",
    due_soon: "Urgent",
    today: "Aujourd'hui",
    yesterday: "Hier",
    students: "étudiants",
    invite_code: "Code d'invitation",
    section_name: "Nom de la section",
    title: "Titre",
    description: "Description",
    deadline: "Date limite",
    max_score: "Note max",
    link: "Lien",
    file: "Fichier",
    content_type: "Type",
    pinned: "Épinglé",
    optional: "Optionnel",
    leave_confirm: "Quitter cette salle ?",
    how_to_join: "Comment rejoindre",
    tip_1: "Demandez le code à votre enseignant",
    tip_2: "Entrez le code ci-dessus et appuyez sur Rejoindre",
    tip_3: "Vous serez ajouté à la salle instantanément",
    open_room: "Ouvrir la salle",
    all_caught_up: "Vous êtes à jour !",
    no_notif_desc: "Aucune notification",
    unread: "non lues",
    teacher_view: "Vue enseignant",
    teacher_grades_desc:
      "L'aperçu des notes est pour les étudiants. Voir les notes dans chaque salle.",
    no_grades_desc: "Vos notes apparaîtront ici une fois les devoirs corrigés",
    overall_average: "Moyenne générale",
    graded_count: "Corrigés",
    your_performance: "Vos résultats",
    graded_assignments: "devoir(s) corrigé(s)",
    total: "Total",
    first_name: "Prénom",
    last_name: "Nom",
    institution: "Établissement",
    bio: "Bio",
    security: "Sécurité",
    two_fa: "Authentification à deux facteurs",
    enabled: "Activé",
    disabled: "Désactivé",
    setup_2fa: "Configurer 2FA",
    scan_qr: "Scannez ce QR code avec votre appli d'authentification",
    verification_code: "Code de vérification",
    verify_enable: "Vérifier et activer",
    about: "À propos",
    edit: "Modifier",
    not_set: "Non défini",
    profile_updated: "Profil mis à jour !",
    profile_update_failed: "Échec de la mise à jour.",
    create_first: "Créez votre première salle",
    join_with_code: "Rejoignez une salle avec un code d'invitation",
    copy_secret: "Copier le secret",
    copied: "Copié !",
    read_more: "Lire la suite",
    show_less: "Réduire",
    appearance: "Apparence",
    theme: "Thème",
    dark_mode: "Mode sombre",
    light_mode: "Mode clair",
  },
    good_morning: "Good morning",
    good_afternoon: "Good afternoon",
    good_evening: "Good evening",
    your_rooms: "Your Rooms",
    no_rooms: "No rooms yet",
    create_room: "Create Room",
    join_room: "Join Room",
    my_grades: "My Grades",
    refresh: "Refresh",
    home: "Home",
    explore: "Explore",
    grades: "Grades",
    notifications: "Alerts",
    profile: "Profile",
    create: "Create",
    content: "Content",
    tasks: "Tasks",
    news: "News",
    no_content: "No content yet",
    no_assignments: "No assignments yet",
    no_announcements: "No announcements yet",
    loading: "Loading...",
    error: "Error",
    cancel: "Cancel",
    save: "Save",
    submit: "Submit",
    delete: "Delete",
    leave_room: "Leave Room",
    add_section: "Add Section",
    add_content: "Add Content",
    add_assignment: "Add Assignment",
    add_announcement: "New Announcement",
    your_submission: "Your Submission",
    submitted: "Submitted",
    graded: "Graded",
    settings: "Settings",
    language: "Language",
    logout: "Log out",
    version: "Version",
    made_by: "Made by",
    enter_code: "Enter invite code...",
    join: "Join",
    mark_all_read: "Mark all read",
    delete_all: "Delete all",
    no_notifications: "No notifications",
    overall_avg: "Overall Avg",
    rooms: "Rooms",
    no_grades: "No grades yet",
    welcome_back: "Welcome back",
    sign_in: "Sign In",
    create_account: "Create Account",
    comments: "Comments",
    add_comment: "Add a comment...",
    post: "Post",
    no_comments: "No comments yet",
    no_deadline: "No deadline",
    past_due: "Past due",
    due_soon: "Due soon",
    today: "Today",
    yesterday: "Yesterday",
    students: "students",
    invite_code: "Invite Code",
    section_name: "Section name",
    title: "Title",
    description: "Description",
    deadline: "Deadline",
    max_score: "Max score",
    link: "Link",
    file: "File",
    content_type: "Type",
    pinned: "Pinned",
    optional: "Optional",
    leave_confirm: "Leave this room?",
    how_to_join: "How to join",
    tip_1: "Ask your teacher for the 8-character invite code",
    tip_2: "Enter the code above and press Join",
    tip_3: "You'll be added to the room instantly",
    open_room: "Open Room",
    all_caught_up: "All caught up!",
    no_notif_desc: "You have no notifications",
    unread: "unread",
    teacher_view: "Teacher View",
    teacher_grades_desc:
      "Grade overview is available for students. View grades in each room's assignments.",
    no_grades_desc: "Your grades will appear here once assignments are graded",
    overall_average: "Overall Average",
    graded_count: "Graded",
    your_performance: "Your academic performance",
    graded_assignments: "graded assignment(s)",
    total: "Total",
    first_name: "First Name",
    last_name: "Last Name",
    institution: "Institution",
    bio: "Bio",
    security: "Security",
    two_fa: "Two-Factor Authentication",
    enabled: "Enabled",
    disabled: "Disabled",
    setup_2fa: "Set Up 2FA",
    scan_qr: "Scan this QR code with your authenticator app",
    verification_code: "Verification Code",
    verify_enable: "Verify & Enable",
    about: "About",
    edit: "Edit",
    not_set: "Not set",
    profile_updated: "Profile updated!",
    profile_update_failed: "Failed to update profile.",
    create_first: "Create your first classroom",
    join_with_code: "Join a room with an invite code",
    copy_secret: "Copy secret",
    copied: "Copied!",
    read_more: "Read more",
    show_less: "Show less",
    appearance: "Appearance",
    theme: "Theme",
    dark_mode: "Dark mode",
    light_mode: "Light mode",
  },
  ar_tn: {
    good_morning: "صباح الخير",
    good_afternoon: "مسا الخير",
    good_evening: "مسا النور",
    your_rooms: "قاعاتك",
    no_rooms: "ما فماش قاعات",
    create_room: "سوّق قاعة",
    join_room: "دخل قاعة",
    my_grades: "نتائجي",
    refresh: "حدّث",
    home: "الرئيسية",
    explore: "اكتشف",
    grades: "النتائج",
    notifications: "الإشعارات",
    profile: "الملف",
    create: "سوّق",
    content: "المحتوى",
    tasks: "الواجبات",
    news: "الأخبار",
    no_content: "ما فماش محتوى",
    no_assignments: "ما فماش واجبات",
    no_announcements: "ما فماش إعلانات",
    loading: "يتحمّل...",
    error: "خطأ",
    cancel: "باطل",
    save: "حفظ",
    submit: "سلّم",
    delete: "امسح",
    leave_room: "اخرج من القاعة",
    add_section: "زيد فصل",
    add_content: "زيد محتوى",
    add_assignment: "زيد واجب",
    add_announcement: "إعلان جديد",
    your_submission: "تسليمك",
    submitted: "تسلّم",
    graded: "مصحّح",
    settings: "الإعدادات",
    language: "اللغة",
    logout: "اخرج",
    version: "الإصدار",
    made_by: "صنع بيدو",
    enter_code: "حط الكود...",
    join: "دخل",
    mark_all_read: "علّم كلش مقروء",
    delete_all: "احذف كلش",
    no_notifications: "ما فماش إشعارات",
    overall_avg: "المعدل",
    rooms: "القاعات",
    no_grades: "ما فماش نتائج",
    welcome_back: "مرحبا بيك",
    sign_in: "دخل",
    create_account: "سجّل",
    comments: "التعليقات",
    add_comment: "زيد تعليق...",
    post: "نشر",
    no_comments: "ما فماش تعليقات",
    no_deadline: "بلا أجل",
    past_due: "فات الأجل",
    due_soon: "يحلّ قريب",
    today: "اليوم",
    yesterday: "أمس",
    students: "طلاب",
    invite_code: "كود الدعوة",
    section_name: "اسم الفصل",
    title: "العنوان",
    description: "الوصف",
    deadline: "أجل التسليم",
    max_score: "أقصى نقطة",
    link: "رابط",
    file: "ملف",
    content_type: "النوع",
    pinned: "مثبّت",
    optional: "اختياري",
    leave_confirm: "تخرج من القاعة؟",
    how_to_join: "كيفاش تدخل",
    tip_1: "اسأل الأستاذ على الكود",
    tip_2: "حط الكود فوق واضغط دخل",
    tip_3: "تتزاد فالقاعة دغري",
    open_room: "افتح القاعة",
    all_caught_up: "كلشي تمام!",
    no_notif_desc: "ما فماش إشعارات",
    unread: "ما قريتهمش",
    teacher_view: "واجهة الأستاذ",
    teacher_grades_desc: "النتائج خاصة بالطلاب. شوف النتائج فكل قاعة.",
    no_grades_desc: "نتائجك تظهر هنا كي يصلّحوا",
    overall_average: "المعدل العام",
    graded_count: "مصلّح",
    your_performance: "نتائجك",
    graded_assignments: "واجب(ات) مصلّح",
    total: "المجموع",
    first_name: "الاسم",
    last_name: "اللقب",
    institution: "المؤسسة",
    bio: "نبذة",
    security: "الأمان",
    two_fa: "المصادقة الثنائية",
    enabled: "مفعّل",
    disabled: "معطّل",
    setup_2fa: "تفعيل 2FA",
    scan_qr: "امسح QR بتطبيق المصادقة",
    verification_code: "كود التحقق",
    verify_enable: "تحقق وفعّل",
    about: "حول",
    edit: "عدّل",
    not_set: "ما مخدومش",
    profile_updated: "تبدّل الملف!",
    profile_update_failed: "ما نجمش نبدّل.",
    create_first: "سوّق أول قاعة",
    join_with_code: "دخل قاعة بالكود",
    copy_secret: "انسخ السر",
    copied: "تنسخ!",
    read_more: "اقرأ أكثر",
    show_less: "أقل",
    appearance: "المظهر",
    theme: "السمة",
    dark_mode: "الوضع الداكن",
    light_mode: "الوضع الفاتح",
  },
};

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const LANG_LABELS: Record<Lang, string> = {
  fr: "Français",
  en: "English",
  ar_tn: "تونسي",
};

export const LANG_OPTIONS: { value: Lang; label: string; flag: string }[] = [
  { value: "fr", label: "Français", flag: "🇫🇷" },
  { value: "en", label: "English", flag: "🇬🇧" },
  { value: "ar_tn", label: "تونسي", flag: "🇹🇳" },
];

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const stored = localStorage.getItem("app_language") as Lang | null;
  const [lang, setLangState] = useState<Lang>(stored || "fr");

  const setLang = (newLang: Lang) => {
    localStorage.setItem("app_language", newLang);
    setLangState(newLang);
    document.documentElement.dir = newLang === "ar_tn" ? "rtl" : "ltr";
    document.documentElement.lang = newLang === "ar_tn" ? "ar" : newLang;
  };

  useEffect(() => {
    document.documentElement.dir = lang === "ar_tn" ? "rtl" : "ltr";
    document.documentElement.lang = lang === "ar_tn" ? "ar" : lang;
  }, [lang]);

  const t = (key: TranslationKey): string => {
    return (
      (translations[lang] as any)[key] ?? (translations.en as any)[key] ?? key
    );
  };

  return (
    <LanguageContext.Provider
      value={{ lang, setLang, t, isRTL: lang === "ar_tn" }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export { LANG_LABELS };
