import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  fr: {
    // Sidebar
    'sidebar.menu': 'Menu',
    'sidebar.dashboard': 'Tableau de bord',
    'sidebar.notifications': 'Notifications',
    'sidebar.profile': 'Profil',
    'sidebar.settings': 'Paramètres',
    'sidebar.toggleTheme': 'Changer le thème',
    'sidebar.logout': 'Déconnexion',
    'sidebar.teacher': 'Professeur',
    'sidebar.student': 'Étudiant',

    // Dashboard
    'dashboard.welcome': 'Bienvenue,',
    'dashboard.teacherSubtitle': 'Gérez vos classes et vos devoirs',
    'dashboard.studentSubtitle': 'Vos classes inscrites',
    'dashboard.createRoom': 'Créer une salle',
    'dashboard.joinRoom': 'Rejoindre une salle',
    'dashboard.yourRooms': 'Vos Salles',
    'dashboard.enrolledRooms': 'Salles Inscrites',
    'dashboard.noRoomsTeacher': 'Aucune salle pour le moment',
    'dashboard.noRoomsStudent': "Vous n'êtes inscrit à aucune salle",
    'dashboard.noRoomsTeacherDesc': 'Créez votre première classe pour commencer.',
    'dashboard.noRoomsStudentDesc': "Rejoignez une salle en utilisant un code d'invitation de votre professeur.",
    'dashboard.students': 'étudiants',
    'dashboard.teacher': 'Professeur',
    'dashboard.noDescription': 'Pas de description',
    'dashboard.deleteRoom': 'Supprimer la salle',
    'dashboard.leaveRoom': 'Quitter la salle',
    'dashboard.loadError': 'Échec du chargement des salles.',
    'dashboard.roomCreated': 'Salle créée !',
    'dashboard.createError': 'Échec de la création de la salle.',
    'dashboard.roomDeleted': 'Salle supprimée',
    'dashboard.deleteError': 'Erreur lors de la suppression',
    'dashboard.leftRoom': 'Vous avez quitté la salle',
    'dashboard.leaveError': 'Erreur lors de la sortie',
    'dashboard.invalidCode': "Code d'invitation invalide.",
    'dashboard.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette salle ?',
    'dashboard.confirmLeave': 'Êtes-vous sûr de vouloir quitter cette salle ?',

    // Create Room Modal
    'createRoom.title': 'Créer une salle',
    'createRoom.name': 'Nom de la salle',
    'createRoom.namePlaceholder': 'ex: Informatique 101',
    'createRoom.subject': 'Matière',
    'createRoom.subjectPlaceholder': 'ex: Informatique',
    'createRoom.description': 'Description',
    'createRoom.descPlaceholder': 'Brève description...',
    'createRoom.colorTheme': 'Thème de couleur',
    'createRoom.creating': 'Création...',
    'createRoom.create': 'Créer la salle',

    // Join Room Modal
    'joinRoom.title': 'Rejoindre une salle',
    'joinRoom.codePlaceholder': 'Saisissez le code à 8 caractères',
    'joinRoom.codeLabel': "Code d'invitation",
    'joinRoom.codeHint': "Demandez le code d'invitation de la salle à votre professeur.",
    'joinRoom.joining': 'Connexion...',
    'joinRoom.join': 'Rejoindre la salle',

    // Common
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.loading': 'Chargement...',
    'common.justNow': "à l'instant",
    'common.days': 'Jours',
    'common.hours': 'Hrs',
    'common.minutes': 'Min',
    'common.seconds': 'Sec',

    // Room Detail
    'room.dashboard': 'Tableau de bord',
    'room.inviteCode': "Code d'invitation",
    'room.copy': 'Copier',
    'room.codeCopied': 'Code copié !',
    'room.copyFailed': 'Échec de la copie',
    'room.fullscreenCode': 'Afficher en plein écran',
    'room.exitFullscreen': 'Fermer',
    'room.clickToClose': 'Cliquez n\'importe où pour fermer',
    'room.loadError': 'Échec du chargement de la salle.',
    'room.notFound': 'Salle non trouvée',
    'room.content': 'Contenu',
    'room.assignments': 'Devoirs',
    'room.announcements': 'Annonces',
    'room.members': 'Membres',
    'room.addContent': 'Ajouter du contenu',
    'room.newSection': 'Nouvelle section',
    'room.noContent': 'Aucun contenu pour le moment',
    'room.noContentInSection': 'Aucun contenu dans cette section.',
    'room.newAssignment': 'Nouveau devoir',
    'room.noAssignments': 'Aucun devoir pour le moment',
    'room.pastDeadline': 'Date limite dépassée',
    'room.late': 'En retard',
    'room.submitted': 'Soumis',
    'room.unsubmitted': 'non soumis',
    'room.submissions': 'soumissions',
    'room.attachFiles': 'Joindre des fichiers',
    'room.submittedFiles': 'Fichiers soumis :',
    'room.sending': 'Envoi...',
    'room.submitAssignment': 'Envoyer le devoir',
    'room.newAnnouncement': 'Nouvelle annonce',
    'room.noAnnouncements': 'Aucune annonce pour le moment',
    'room.pinned': 'Épinglée',
    'room.comments': 'commentaires',
    'room.pendingRequests': 'Demandes en attente',
    'room.approve': 'Approuver',
    'room.reject': 'Rejeter',
    'room.noMembers': 'Aucun membre pour le moment',
    'room.shareTip': "Partagez le code d'invitation avec vos étudiants.",
    'room.selectedStudents': 'étudiant(s) sélectionné(s)',
    'room.expelSelected': 'Expulser la sélection',
    'room.approved': 'Approuvé !',
    'room.removed': 'Supprimé !',
    'room.actionFailed': "Échec de l'opération.",
    'room.expelled': 'Étudiants expulsés !',
    'room.uploadSuccess': 'Contenu téléversé !',
    'room.uploadError': 'Échec du téléversement.',
    'room.assignmentCreated': 'Devoir créé !',
    'room.assignmentError': 'Échec de la création du devoir.',
    'room.announcementPublished': 'Annonce publiée !',
    'room.announcementError': 'Échec de la publication.',
    'room.sectionAdded': 'Section ajoutée !',
    'room.sectionError': 'Échec.',
    'room.submissionSuccess': 'Soumis avec succès !',
    'room.submissionError': 'Échec de la soumission.',
    'room.preview': 'Aperçu',
    'room.download': 'Télécharger',
    'room.edit': 'Modifier',
    'room.editSuccess': 'Modifié avec succès !',
    'room.editError': 'Échec de la modification.',
    'room.tpAutoAssignment': 'Un devoir a été créé automatiquement (délai: 1 semaine)',
    'room.tpAutoHint': 'Sélectionner TP crée automatiquement un devoir avec un délai d\'une semaine.',
    'room.refreshNow': 'Actualiser maintenant',
    'room.allSubmissions': 'Toutes les soumissions',
    'room.noSubmissionsYet': 'Aucune soumission pour le moment.',
    'room.grade': 'Noter',
    'room.graded': 'Note attribuée !',
    'room.score': 'Note',
    'room.feedback': 'Commentaire',
    'room.feedbackPlaceholder': 'Commentaire optionnel...',
    'room.confirmDeleteSubmission': 'Supprimer votre soumission ? Vous pourrez en soumettre une nouvelle.',
    'room.submissionDeleted': 'Soumission supprimée. Vous pouvez resoumettre.',
    'room.deleteAndResubmit': 'Supprimer et resoumettre',
    'room.delete': 'Supprimer',
    'room.confirmDeleteContent': 'Supprimer ce contenu définitivement ?',
    'room.contentDeleted': 'Contenu supprimé.',
    'room.confirmDeleteAssignment': 'Supprimer ce devoir et toutes les soumissions ?',
    'room.assignmentDeleted': 'Devoir supprimé.',
    'room.confirmDeleteAnnouncement': 'Supprimer cette annonce ?',
    'room.announcementDeleted': 'Annonce supprimée.',
    'room.noComments': 'Aucun commentaire pour le moment.',
    'room.writeComment': 'Écrire un commentaire...',
    'room.postComment': 'Publier',
    'room.roomSettings': 'Paramètres de la salle',
    'room.roomUpdated': 'Salle mise à jour.',
    'room.nameLabel': 'Nom',
    'room.subjectLabel': 'Matière',
    'room.descriptionLabel': 'Description',
    'room.colorLabel': 'Couleur',
    'common.saving': 'Enregistrement...',
    'common.loading': 'Chargement...',

    // Upload Modal
    'upload.title': 'Ajouter du contenu',
    'upload.titleLabel': 'Titre',
    'upload.type': 'Type',
    'upload.section': 'Section',
    'upload.none': 'Aucune',
    'upload.lecture': 'Cours',
    'upload.tp': 'TP',
    'upload.exam': 'Examen',
    'upload.resource': 'Ressource',
    'upload.link': 'Lien',
    'upload.url': 'URL',
    'upload.file': 'Fichier',
    'upload.dropHint': 'Cliquez ou glissez un fichier ici',
    'upload.maxSize': 'Maximum 50 Mo',
    'upload.adding': 'Envoi...',
    'upload.add': 'Ajouter',

    // Assignment Modal
    'assignmentModal.title': 'Nouveau devoir',
    'assignmentModal.titleLabel': 'Titre',
    'assignmentModal.description': 'Description',
    'assignmentModal.deadline': 'Date limite',
    'assignmentModal.maxGrade': 'Note maximale',
    'assignmentModal.creating': 'Création...',
    'assignmentModal.create': 'Créer le devoir',

    // Announcement Modal
    'announceModal.title': 'Publier une annonce',
    'announceModal.titleLabel': 'Titre',
    'announceModal.message': 'Message',
    'announceModal.publishing': 'Publication...',
    'announceModal.publish': 'Publier',

    // Section Modal
    'sectionModal.title': 'Ajouter une section',
    'sectionModal.nameLabel': 'Nom de la section',
    'sectionModal.namePlaceholder': 'ex: Semaine 1, Chapitre 3',
    'sectionModal.add': 'Ajouter',

    // Profile
    'profile.title': 'Profil',
    'profile.subtitle': 'Gérez les paramètres de votre compte',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom de famille',
    'profile.bio': 'Biographie',
    'profile.bioPlaceholder': 'Parlez-nous de vous...',
    'profile.institution': 'Institution',
    'profile.institutionPlaceholder': 'ex: Université des Sciences',
    'profile.saving': 'Enregistrement...',
    'profile.saveChanges': 'Enregistrer les modifications',
    'profile.updateSuccess': 'Profil mis à jour !',
    'profile.updateError': 'Échec de la mise à jour du profil.',
    'profile.teacher': 'Professeur',
    'profile.student': 'Étudiant',
    'profile.emailVerified': 'Email vérifié',
    'profile.emailNotVerified': 'Non vérifié',
    'profile.verifyNow': 'Vérifier maintenant',
    'profile.resendCode': 'Renvoyer le code',
    'profile.codeSent': 'Code de vérification envoyé !',
    'profile.resendError': "Erreur lors de l'envoi.",
    'profile.language': "Langue de l'interface",

    // 2FA
    '2fa.title': 'Authentification à deux facteurs (2FA)',
    '2fa.enabledDesc': 'La 2FA est activée pour votre compte.',
    '2fa.disabledDesc': 'Ajoutez une couche de sécurité supplémentaire.',
    '2fa.enabled': '2FA activé',
    '2fa.disabling': 'Désactivation...',
    '2fa.disable': 'Désactiver la 2FA',
    '2fa.confirmDisable': 'Êtes-vous sûr de vouloir désactiver la 2FA ?',
    '2fa.scanQR': "Scannez ce QR code avec votre application d'authentification (Google Authenticator, Authy, etc.)",
    '2fa.verificationCode': 'Code de vérification',
    '2fa.verifying': 'Vérification...',
    '2fa.confirm': 'Confirmer',
    '2fa.enabling': 'Chargement...',
    '2fa.enable': 'Activer la 2FA',
    '2fa.activated': '2FA activé !',
    '2fa.deactivated': '2FA désactivé.',
    '2fa.invalidCode': 'Code invalide.',
    '2fa.error': 'Erreur.',
    '2fa.reminderTitle': 'Protégez votre compte',
    '2fa.reminderDesc': 'Votre compte n\'a pas encore l\'authentification à deux facteurs (2FA) activée. Activez-la pour protéger votre compte contre les accès non autorisés.',
    '2fa.reminderLater': 'Plus tard',
    '2fa.reminderActivate': 'Activer maintenant',

    // Notifications
    'notifs.title': 'Notifications',
    'notifs.subtitle': 'Restez informé de tout ce qui se passe dans vos classes',
    'notifs.markAllRead': 'Tout marquer comme lu',
    'notifs.allRead': 'Tout a été marqué comme lu.',
    'notifs.none': 'Aucune notification',
    'notifs.upToDate': 'Vous êtes à jour !',
    'notifs.loadError': 'Échec du chargement des notifications.',
    'notifs.deleteAll': 'Tout supprimer',
    'notifs.confirmDeleteAll': 'Supprimer toutes les notifications ?',
    'notifs.allDeleted': 'Toutes les notifications ont été supprimées.',

    // Login
    'login.welcome': 'Bon retour',
    'login.subtitle': 'Connectez-vous à votre compte',
    'login.2faTitle': 'Vérification 2FA',
    'login.2faSubtitle': "Entrez le code de votre application d'authentification",
    'login.email': 'Email',
    'login.emailPlaceholder': 'vous@universite.edu',
    'login.password': 'Mot de passe',
    'login.2faCode': 'Code 2FA',
    'login.connecting': 'Connexion...',
    'login.verify': 'Vérifier',
    'login.connect': 'Se connecter',
    'login.back': 'Retour',
    'login.noAccount': "Vous n'avez pas de compte ?",
    'login.signup': "S'inscrire",
    'login.success': 'Bon retour parmi nous !',
    'login.error': 'Email ou mot de passe invalide.',
    'login.forgotPassword': 'Mot de passe oublié ?',

    // Forgot Password
    'forgot.title': 'Mot de passe oublié',
    'forgot.subtitle': 'Entrez votre email pour recevoir un code de réinitialisation',
    'forgot.sendCode': 'Envoyer le code',
    'forgot.sending': 'Envoi...',
    'forgot.codeSent': 'Code envoyé ! Vérifiez votre email.',
    'forgot.codeLabel': 'Code de réinitialisation',
    'forgot.newPassword': 'Nouveau mot de passe',
    'forgot.confirmPassword': 'Confirmer le mot de passe',
    'forgot.resetTitle': 'Réinitialiser le mot de passe',
    'forgot.resetDesc': 'Entrez le code reçu par email à',
    'forgot.resetButton': 'Réinitialiser',
    'forgot.resetting': 'Réinitialisation...',
    'forgot.resetSuccess': 'Mot de passe réinitialisé avec succès !',
    'forgot.doneTitle': 'Mot de passe modifié',
    'forgot.doneDesc': 'Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    'forgot.backToLogin': 'Retour à la connexion',
    'forgot.error': 'Une erreur est survenue.',

    // Signup
    'signup.title': 'Créer un compte',
    'signup.subtitle': 'Rejoignez la plateforme conçue pour la concentration',
    'signup.iAm': 'Je suis...',
    'signup.firstName': 'Prénom',
    'signup.firstNamePlaceholder': 'Jean',
    'signup.lastName': 'Nom',
    'signup.lastNamePlaceholder': 'Dupont',
    'signup.email': 'Email',
    'signup.emailPlaceholder': 'vous@universite.edu',
    'signup.password': 'Mot de passe',
    'signup.passwordPlaceholder': 'Min 8 caractères',
    'signup.confirmPassword': 'Confirmer le mot de passe',
    'signup.confirmPlaceholder': 'Répétez votre mot de passe',
    'signup.passwordsMatch': '✓ Les mots de passe correspondent',
    'signup.passwordsMismatch': '✗ Les mots de passe ne correspondent pas',
    'signup.teacher': 'Professeur',
    'signup.student': 'Étudiant',
    'signup.creating': 'Création en cours...',
    'signup.create': 'Créer un compte',
    'signup.hasAccount': 'Vous avez déjà un compte ?',
    'signup.login': 'Se connecter',
    'signup.success': 'Compte créé ! Vérifiez votre email.',
    'signup.error': 'Une erreur est survenue. Veuillez réessayer.',
    'signup.passwordMismatch': 'Les mots de passe ne correspondent pas.',
    'signup.passwordTooShort': 'Le mot de passe doit comporter au moins 8 caractères.',
    'signup.weak': 'Faible',
    'signup.fair': 'Moyen',
    'signup.good': 'Bon',
    'signup.strong': 'Fort',

    // Verify Email
    'verify.title': "Vérification de l'email",
    'verify.subtitle': 'Un code à 6 chiffres a été envoyé à',
    'verify.codeLabel': 'Code de vérification',
    'verify.verifying': 'Vérification...',
    'verify.verify': 'Vérifier',
    'verify.resending': 'Envoi en cours...',
    'verify.resend': 'Renvoyer le code',
    'verify.spamHint': 'Vérifiez également votre dossier spam.',
    'verify.success': 'Email vérifié avec succès !',
    'verify.invalidCode': 'Code invalide.',
    'verify.codeSent': 'Code renvoyé à votre email.',
    'verify.sendError': "Erreur lors de l'envoi.",
    'verify.enter6Digits': 'Veuillez entrer un code à 6 chiffres.',

    // Landing
    'landing.login': 'Se connecter',
    'landing.getStarted': 'Démarrer',
    'landing.heroTitle': 'La salle de classe,',
    'landing.heroTitle2': 'Réinventée.',
    'landing.heroDesc': "Une plateforme moderne conçue pour les universités. Créez des salles, partagez du contenu, collectez des devoirs et notez — le tout dans une interface élégante et épurée.",
    'landing.startTeaching': 'Commencer à Enseigner',
    'landing.joinStudent': "Rejoindre en tant qu'Étudiant",
    'landing.focusTitle': 'Conçu pour la',
    'landing.focusHighlight': 'Concentration',
    'landing.focusDesc': "Tout ce que vous souhaitiez que les systèmes d'apprentissage standards fassent, conçu avec une attention méticuleuse aux détails.",
    'landing.feature1Title': 'Salles Magnifiques',
    'landing.feature1Desc': 'Couleurs personnalisées, mode sombre — des classes qui inspirent.',
    'landing.feature2Title': 'Glisser-Déposer',
    'landing.feature2Desc': 'Téléversez des cours, TP et ressources en quelques secondes.',
    'landing.feature3Title': 'Délais Intelligents',
    'landing.feature3Desc': 'Comptes à rebours, suivi des retards, rappels automatiques.',
    'landing.feature4Title': 'Correction Instantanée',
    'landing.feature4Desc': 'Notez les soumissions avec des retours en un clic.',
    'landing.feature5Title': 'Annonces',
    'landing.feature5Desc': 'Publiez des annonces avec commentaires et fils de discussion.',
    'landing.feature6Title': 'Notifications',
    'landing.feature6Desc': 'Alertes en temps réel pour les devoirs, les notes et plus.',
    'landing.footer': "Conçu avec une ingénierie de précision par Aymen HM",

    // Grades page
    'grades.title': 'Mes Notes',
    'grades.subtitle': 'Consultez toutes vos notes à travers toutes vos salles',
    'grades.loadError': 'Échec du chargement des notes.',
    'grades.noGrades': 'Aucune note pour le moment',
    'grades.noGradesDesc': 'Vos notes apparaîtront ici une fois que vos professeurs auront noté vos devoirs.',
    'grades.gradedRooms': 'Salles notées',
    'grades.totalGrades': 'Total des notes',
    'grades.overallAverage': 'Moyenne globale',
    'grades.assignment': 'Devoir',
    'grades.score': 'Note',
    'grades.percentage': 'Pourcentage',
    'grades.feedback': 'Commentaire',
    'grades.roomTotal': 'Total salle',

    // Sidebar grades
    'sidebar.grades': 'Notes',

    // Dashboard search
    'dashboard.searchPlaceholder': 'Rechercher une salle...',
    'dashboard.noSearchResults': 'Aucune salle trouvée',

    // Room sort & features
    'room.sortNewest': 'Plus récent',
    'room.sortOldest': 'Plus ancien',
    'room.sortDeadlineAsc': 'Date limite (croissant)',
    'room.sortDeadlineDesc': 'Date limite (décroissant)',
    'room.attachedFile': 'Fichier joint',
    'room.pinAnnouncement': 'Épingler cette annonce',
    'room.pin': 'Épingler',
    'room.unpin': 'Désépingler',
    'room.pinnedSuccess': 'Annonce épinglée !',
    'room.unpinned': 'Annonce désépinglée.',

    // Assignment modal
    'assignmentModal.attachFile': 'Fichier joint (optionnel)',

    // 404
    'notFound.title': 'Page non trouvée',
    'notFound.desc': "La page que vous cherchez n'existe pas ou a été déplacée.",
    'notFound.goHome': 'Retour au tableau de bord',
  },
  en: {
    // Sidebar
    'sidebar.menu': 'Menu',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.notifications': 'Notifications',
    'sidebar.profile': 'Profile',
    'sidebar.settings': 'Settings',
    'sidebar.toggleTheme': 'Toggle Theme',
    'sidebar.logout': 'Log Out',
    'sidebar.teacher': 'Teacher',
    'sidebar.student': 'Student',

    // Dashboard
    'dashboard.welcome': 'Welcome,',
    'dashboard.teacherSubtitle': 'Manage your classes and assignments',
    'dashboard.studentSubtitle': 'Your enrolled classes',
    'dashboard.createRoom': 'Create Room',
    'dashboard.joinRoom': 'Join Room',
    'dashboard.yourRooms': 'Your Rooms',
    'dashboard.enrolledRooms': 'Enrolled Rooms',
    'dashboard.noRoomsTeacher': 'No rooms yet',
    'dashboard.noRoomsStudent': "You're not enrolled in any room",
    'dashboard.noRoomsTeacherDesc': 'Create your first class to get started.',
    'dashboard.noRoomsStudentDesc': 'Join a room using an invite code from your teacher.',
    'dashboard.students': 'students',
    'dashboard.teacher': 'Teacher',
    'dashboard.noDescription': 'No description',
    'dashboard.deleteRoom': 'Delete room',
    'dashboard.leaveRoom': 'Leave room',
    'dashboard.loadError': 'Failed to load rooms.',
    'dashboard.roomCreated': 'Room created!',
    'dashboard.createError': 'Failed to create room.',
    'dashboard.roomDeleted': 'Room deleted',
    'dashboard.deleteError': 'Error deleting room',
    'dashboard.leftRoom': 'You left the room',
    'dashboard.leaveError': 'Error leaving room',
    'dashboard.invalidCode': 'Invalid invite code.',
    'dashboard.confirmDelete': 'Are you sure you want to delete this room?',
    'dashboard.confirmLeave': 'Are you sure you want to leave this room?',

    // Create Room Modal
    'createRoom.title': 'Create Room',
    'createRoom.name': 'Room Name',
    'createRoom.namePlaceholder': 'e.g. Computer Science 101',
    'createRoom.subject': 'Subject',
    'createRoom.subjectPlaceholder': 'e.g. Computer Science',
    'createRoom.description': 'Description',
    'createRoom.descPlaceholder': 'Brief description...',
    'createRoom.colorTheme': 'Color Theme',
    'createRoom.creating': 'Creating...',
    'createRoom.create': 'Create Room',

    // Join Room Modal
    'joinRoom.title': 'Join Room',
    'joinRoom.codePlaceholder': 'Enter 8-character code',
    'joinRoom.codeLabel': 'Invite Code',
    'joinRoom.codeHint': 'Ask your teacher for the room invite code.',
    'joinRoom.joining': 'Joining...',
    'joinRoom.join': 'Join Room',

    // Common
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.justNow': 'just now',
    'common.days': 'Days',
    'common.hours': 'Hrs',
    'common.minutes': 'Min',
    'common.seconds': 'Sec',

    // Room Detail
    'room.dashboard': 'Dashboard',
    'room.inviteCode': 'Invite Code',
    'room.copy': 'Copy',
    'room.codeCopied': 'Code copied!',
    'room.copyFailed': 'Copy failed',
    'room.fullscreenCode': 'Show fullscreen',
    'room.exitFullscreen': 'Close',
    'room.clickToClose': 'Click anywhere to close',
    'room.loadError': 'Failed to load room.',
    'room.notFound': 'Room not found',
    'room.content': 'Content',
    'room.assignments': 'Assignments',
    'room.announcements': 'Announcements',
    'room.members': 'Members',
    'room.addContent': 'Add Content',
    'room.newSection': 'New Section',
    'room.noContent': 'No content yet',
    'room.noContentInSection': 'No content in this section.',
    'room.newAssignment': 'New Assignment',
    'room.noAssignments': 'No assignments yet',
    'room.pastDeadline': 'Past deadline',
    'room.late': 'Late',
    'room.submitted': 'Submitted',
    'room.unsubmitted': 'not submitted',
    'room.submissions': 'submissions',
    'room.attachFiles': 'Attach Files',
    'room.submittedFiles': 'Submitted files:',
    'room.sending': 'Sending...',
    'room.submitAssignment': 'Submit',
    'room.newAnnouncement': 'New Announcement',
    'room.noAnnouncements': 'No announcements yet',
    'room.pinned': 'Pinned',
    'room.comments': 'comments',
    'room.pendingRequests': 'Pending requests',
    'room.approve': 'Approve',
    'room.reject': 'Reject',
    'room.noMembers': 'No members yet',
    'room.shareTip': 'Share the invite code with your students.',
    'room.selectedStudents': 'student(s) selected',
    'room.expelSelected': 'Remove Selected',
    'room.approved': 'Approved!',
    'room.removed': 'Removed!',
    'room.actionFailed': 'Operation failed.',
    'room.expelled': 'Students removed!',
    'room.uploadSuccess': 'Content uploaded!',
    'room.uploadError': 'Upload failed.',
    'room.assignmentCreated': 'Assignment created!',
    'room.assignmentError': 'Failed to create assignment.',
    'room.announcementPublished': 'Announcement published!',
    'room.announcementError': 'Failed to publish.',
    'room.sectionAdded': 'Section added!',
    'room.sectionError': 'Failed.',
    'room.submissionSuccess': 'Submitted successfully!',
    'room.submissionError': 'Submission failed.',
    'room.preview': 'Preview',
    'room.download': 'Download',
    'room.edit': 'Edit',
    'room.editSuccess': 'Updated successfully!',
    'room.editError': 'Update failed.',
    'room.tpAutoAssignment': 'An assignment was automatically created (deadline: 1 week)',
    'room.tpAutoHint': 'Selecting TP automatically creates an assignment with a 1-week deadline.',
    'room.refreshNow': 'Refresh now',
    'room.allSubmissions': 'All Submissions',
    'room.noSubmissionsYet': 'No submissions yet.',
    'room.grade': 'Grade',
    'room.graded': 'Grade submitted!',
    'room.score': 'Score',
    'room.feedback': 'Feedback',
    'room.feedbackPlaceholder': 'Optional feedback...',
    'room.confirmDeleteSubmission': 'Delete your submission? You can submit a new one.',
    'room.submissionDeleted': 'Submission deleted. You can resubmit.',
    'room.deleteAndResubmit': 'Delete & resubmit',
    'room.delete': 'Delete',
    'room.confirmDeleteContent': 'Delete this content permanently?',
    'room.contentDeleted': 'Content deleted.',
    'room.confirmDeleteAssignment': 'Delete this assignment and all submissions?',
    'room.assignmentDeleted': 'Assignment deleted.',
    'room.confirmDeleteAnnouncement': 'Delete this announcement?',
    'room.announcementDeleted': 'Announcement deleted.',
    'room.noComments': 'No comments yet.',
    'room.writeComment': 'Write a comment...',
    'room.postComment': 'Post',
    'room.roomSettings': 'Room Settings',
    'room.roomUpdated': 'Room updated.',
    'room.nameLabel': 'Name',
    'room.subjectLabel': 'Subject',
    'room.descriptionLabel': 'Description',
    'room.colorLabel': 'Color',
    'common.saving': 'Saving...',
    'common.loading': 'Loading...',

    // Upload Modal
    'upload.title': 'Add Content',
    'upload.titleLabel': 'Title',
    'upload.type': 'Type',
    'upload.section': 'Section',
    'upload.none': 'None',
    'upload.lecture': 'Lecture',
    'upload.tp': 'Practical Work',
    'upload.exam': 'Exam',
    'upload.resource': 'Resource',
    'upload.link': 'Link',
    'upload.url': 'URL',
    'upload.file': 'File',
    'upload.dropHint': 'Click or drag a file here',
    'upload.maxSize': 'Maximum 50 MB',
    'upload.adding': 'Uploading...',
    'upload.add': 'Add',

    // Assignment Modal
    'assignmentModal.title': 'New Assignment',
    'assignmentModal.titleLabel': 'Title',
    'assignmentModal.description': 'Description',
    'assignmentModal.deadline': 'Deadline',
    'assignmentModal.maxGrade': 'Max Grade',
    'assignmentModal.creating': 'Creating...',
    'assignmentModal.create': 'Create Assignment',

    // Announcement Modal
    'announceModal.title': 'Post Announcement',
    'announceModal.titleLabel': 'Title',
    'announceModal.message': 'Message',
    'announceModal.publishing': 'Publishing...',
    'announceModal.publish': 'Publish',

    // Section Modal
    'sectionModal.title': 'Add Section',
    'sectionModal.nameLabel': 'Section Name',
    'sectionModal.namePlaceholder': 'e.g. Week 1, Chapter 3',
    'sectionModal.add': 'Add',

    // Profile
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your account settings',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell us about yourself...',
    'profile.institution': 'Institution',
    'profile.institutionPlaceholder': 'e.g. University of Sciences',
    'profile.saving': 'Saving...',
    'profile.saveChanges': 'Save Changes',
    'profile.updateSuccess': 'Profile updated!',
    'profile.updateError': 'Failed to update profile.',
    'profile.teacher': 'Teacher',
    'profile.student': 'Student',
    'profile.emailVerified': 'Email verified',
    'profile.emailNotVerified': 'Not verified',
    'profile.verifyNow': 'Verify now',
    'profile.resendCode': 'Resend code',
    'profile.codeSent': 'Verification code sent!',
    'profile.resendError': 'Error sending code.',
    'profile.language': 'Interface Language',

    // 2FA
    '2fa.title': 'Two-Factor Authentication (2FA)',
    '2fa.enabledDesc': '2FA is enabled for your account.',
    '2fa.disabledDesc': 'Add an extra layer of security.',
    '2fa.enabled': '2FA enabled',
    '2fa.disabling': 'Disabling...',
    '2fa.disable': 'Disable 2FA',
    '2fa.confirmDisable': 'Are you sure you want to disable 2FA?',
    '2fa.scanQR': 'Scan this QR code with your authenticator app (Google Authenticator, Authy, etc.)',
    '2fa.verificationCode': 'Verification Code',
    '2fa.verifying': 'Verifying...',
    '2fa.confirm': 'Confirm',
    '2fa.enabling': 'Loading...',
    '2fa.enable': 'Enable 2FA',
    '2fa.activated': '2FA enabled!',
    '2fa.deactivated': '2FA disabled.',
    '2fa.invalidCode': 'Invalid code.',
    '2fa.error': 'Error.',
    '2fa.reminderTitle': 'Secure Your Account',
    '2fa.reminderDesc': 'Your account does not have Two-Factor Authentication (2FA) enabled yet. Enable it now to add an extra layer of security and protect your account from unauthorized access.',
    '2fa.reminderLater': 'Maybe Later',
    '2fa.reminderActivate': 'Enable Now',

    // Notifications
    'notifs.title': 'Notifications',
    'notifs.subtitle': 'Stay informed about everything happening in your classes',
    'notifs.markAllRead': 'Mark all as read',
    'notifs.allRead': 'All marked as read.',
    'notifs.none': 'No notifications',
    'notifs.upToDate': "You're up to date!",
    'notifs.loadError': 'Failed to load notifications.',
    'notifs.deleteAll': 'Delete all',
    'notifs.confirmDeleteAll': 'Delete all notifications?',
    'notifs.allDeleted': 'All notifications deleted.',

    // Login
    'login.welcome': 'Welcome Back',
    'login.subtitle': 'Sign in to your account',
    'login.2faTitle': '2FA Verification',
    'login.2faSubtitle': 'Enter the code from your authenticator app',
    'login.email': 'Email',
    'login.emailPlaceholder': 'you@university.edu',
    'login.password': 'Password',
    'login.2faCode': '2FA Code',
    'login.connecting': 'Signing in...',
    'login.verify': 'Verify',
    'login.connect': 'Sign In',
    'login.back': 'Back',
    'login.noAccount': "Don't have an account?",
    'login.signup': 'Sign Up',
    'login.success': 'Welcome back!',
    'login.error': 'Invalid email or password.',
    'login.forgotPassword': 'Forgot password?',

    // Forgot Password
    'forgot.title': 'Forgot Password',
    'forgot.subtitle': 'Enter your email to receive a reset code',
    'forgot.sendCode': 'Send Code',
    'forgot.sending': 'Sending...',
    'forgot.codeSent': 'Code sent! Check your email.',
    'forgot.codeLabel': 'Reset Code',
    'forgot.newPassword': 'New Password',
    'forgot.confirmPassword': 'Confirm Password',
    'forgot.resetTitle': 'Reset Password',
    'forgot.resetDesc': 'Enter the code sent to',
    'forgot.resetButton': 'Reset Password',
    'forgot.resetting': 'Resetting...',
    'forgot.resetSuccess': 'Password reset successfully!',
    'forgot.doneTitle': 'Password Changed',
    'forgot.doneDesc': 'You can now sign in with your new password.',
    'forgot.backToLogin': 'Back to Sign In',
    'forgot.error': 'An error occurred.',

    // Signup
    'signup.title': 'Create Account',
    'signup.subtitle': 'Join the platform designed for focus',
    'signup.iAm': 'I am a...',
    'signup.firstName': 'First Name',
    'signup.firstNamePlaceholder': 'John',
    'signup.lastName': 'Last Name',
    'signup.lastNamePlaceholder': 'Doe',
    'signup.email': 'Email',
    'signup.emailPlaceholder': 'you@university.edu',
    'signup.password': 'Password',
    'signup.passwordPlaceholder': 'Min 8 characters',
    'signup.confirmPassword': 'Confirm Password',
    'signup.confirmPlaceholder': 'Repeat your password',
    'signup.passwordsMatch': '✓ Passwords match',
    'signup.passwordsMismatch': '✗ Passwords do not match',
    'signup.teacher': 'Teacher',
    'signup.student': 'Student',
    'signup.creating': 'Creating...',
    'signup.create': 'Create Account',
    'signup.hasAccount': 'Already have an account?',
    'signup.login': 'Sign In',
    'signup.success': 'Account created! Check your email.',
    'signup.error': 'Something went wrong. Please try again.',
    'signup.passwordMismatch': 'Passwords do not match.',
    'signup.passwordTooShort': 'Password must be at least 8 characters.',
    'signup.weak': 'Weak',
    'signup.fair': 'Fair',
    'signup.good': 'Good',
    'signup.strong': 'Strong',

    // Verify Email
    'verify.title': 'Email Verification',
    'verify.subtitle': 'A 6-digit code was sent to',
    'verify.codeLabel': 'Verification Code',
    'verify.verifying': 'Verifying...',
    'verify.verify': 'Verify',
    'verify.resending': 'Sending...',
    'verify.resend': 'Resend Code',
    'verify.spamHint': 'Also check your spam folder.',
    'verify.success': 'Email verified successfully!',
    'verify.invalidCode': 'Invalid code.',
    'verify.codeSent': 'Code resent to your email.',
    'verify.sendError': 'Error sending code.',
    'verify.enter6Digits': 'Please enter a 6-digit code.',

    // Landing
    'landing.login': 'Sign In',
    'landing.getStarted': 'Get Started',
    'landing.heroTitle': 'The Classroom,',
    'landing.heroTitle2': 'Reinvented.',
    'landing.heroDesc': 'A modern platform designed for universities. Create rooms, share content, collect assignments and grade — all in an elegant, clean interface.',
    'landing.startTeaching': 'Start Teaching',
    'landing.joinStudent': 'Join as Student',
    'landing.focusTitle': 'Designed for',
    'landing.focusHighlight': 'Focus',
    'landing.focusDesc': 'Everything you wished standard learning systems could do, built with meticulous attention to detail.',
    'landing.feature1Title': 'Beautiful Rooms',
    'landing.feature1Desc': 'Custom colors, dark mode — classes that inspire.',
    'landing.feature2Title': 'Drag & Drop',
    'landing.feature2Desc': 'Upload lectures, labs and resources in seconds.',
    'landing.feature3Title': 'Smart Deadlines',
    'landing.feature3Desc': 'Countdowns, late tracking, automatic reminders.',
    'landing.feature4Title': 'Instant Grading',
    'landing.feature4Desc': 'Grade submissions with feedback in one click.',
    'landing.feature5Title': 'Announcements',
    'landing.feature5Desc': 'Post announcements with comments and threads.',
    'landing.feature6Title': 'Notifications',
    'landing.feature6Desc': 'Real-time alerts for assignments, grades and more.',
    'landing.footer': 'Precision-engineered by Aymen HM',

    // Grades page
    'grades.title': 'My Grades',
    'grades.subtitle': 'View all your grades across all your rooms',
    'grades.loadError': 'Failed to load grades.',
    'grades.noGrades': 'No grades yet',
    'grades.noGradesDesc': 'Your grades will appear here once your teachers grade your assignments.',
    'grades.gradedRooms': 'Graded Rooms',
    'grades.totalGrades': 'Total Grades',
    'grades.overallAverage': 'Overall Average',
    'grades.assignment': 'Assignment',
    'grades.score': 'Score',
    'grades.percentage': 'Percentage',
    'grades.feedback': 'Feedback',
    'grades.roomTotal': 'Room total',

    // Sidebar grades
    'sidebar.grades': 'Grades',

    // Dashboard search
    'dashboard.searchPlaceholder': 'Search rooms...',
    'dashboard.noSearchResults': 'No rooms found',

    // Room sort & features
    'room.sortNewest': 'Newest',
    'room.sortOldest': 'Oldest',
    'room.sortDeadlineAsc': 'Deadline (ascending)',
    'room.sortDeadlineDesc': 'Deadline (descending)',
    'room.attachedFile': 'Attached file',
    'room.pinAnnouncement': 'Pin this announcement',
    'room.pin': 'Pin',
    'room.unpin': 'Unpin',
    'room.pinnedSuccess': 'Announcement pinned!',
    'room.unpinned': 'Announcement unpinned.',

    // Assignment modal
    'assignmentModal.attachFile': 'Attach file (optional)',

    // 404
    'notFound.title': 'Page Not Found',
    'notFound.desc': "The page you're looking for doesn't exist or has been moved.",
    'notFound.goHome': 'Back to Dashboard',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_language') || 'fr';
  });

  const changeLanguage = useCallback((lang) => {
    setLanguage(lang);
    localStorage.setItem('app_language', lang);
  }, []);

  const t = useCallback((key) => {
    return translations[language]?.[key] || translations['fr']?.[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
