# Generated by Django 6.0.3 on 2026-03-09 23:33

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_submission_file_submissionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/%Y/%m/', validators=[content.validators.validate_upload_file]),
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content/%Y/%m/', validators=[content.validators.validate_upload_file]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(upload_to='submissions/%Y/%m/', validators=[content.validators.validate_upload_file]),
        ),
    ]
