# Generated by Django 6.0.3 on 2026-03-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_submission_status_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_resubmission',
            field=models.BooleanField(default=False),
        ),
    ]
