# Generated by Django 5.2.12 on 2026-03-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('content', 'New Content'), ('assignment', 'New Assignment'), ('submission', 'New Submission'), ('grade', 'Grade Posted'), ('announcement', 'New Announcement'), ('comment', 'New Comment'), ('deadline', 'Deadline Reminder'), ('room', 'Room Update')], default='room', max_length=30),
        ),
    ]
